### ISSUE TITLE
Update Symbol Bootstrap Docs to the new 0.2.0 changes

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-docs#526]
1) addresess.yml folder has changed from `target/config/generated-addresses/addresses.yml` to `target/addresses.yml`

https://docs.symbolplatform.com/guides/network/creating-a-private-test-net.html#retrieving-the-test-accounts

2) `addresses.yml` mosaics: has changed to:

```
mosaics:
    -
        id: 56631872BA6657A1
        name: currency
        type: currency
        accounts:
            -
                privateKey: 84454560C25B34033D5C692A925B016E223962BA8825C1D5AAFFB8E162E5FC97
                publicKey: 91A9513EBEB50DEFCD928032611B2FBC046FA894089D2ACED115D6EDEB0BFD2A
                address: NBO3P2AM3A6242V2NFMUIG5RQ3ZFDRKS5QNRBJA
            -
                privateKey: DB8AF673988F9CB7CB079530041D4A27C3090FFBCE51B6F15F936D715F19F87A
                publicKey: 4E9CC90B45265691C2CF0C68785A06602D28DB50ACFB91F8389B976898239132
                address: NCDFN3W2AP3E4I2XYITUJHHGVSYKOIR2IUTXKXY
    -
        id: 079C43E0DFC44B38
        name: harvest
        type: harvest
        accounts:
            -
                privateKey: D7AED13A1F5440CBD96670177E4DBA8489A78DBC98C39F4A4D7F97A63D32B777
                publicKey: D617FC0C746681849D93DBEB5FE0E390F26535E4EA76F02AB206AD053B72FAB8
                address: NBFFJ3MNPMHP474KD7JLBJWAYSYSAUEW7L7262Q
            -
                privateKey: 879551B9A06F4795BD38C828525BD6C10D0194484DF5CF50BC3CCEB517E54640
                publicKey: BBB04EC2CF67658B755F94FC347DDC4AAFFBFC24B84298AEF41CDA2485FA216E
                address: NCQBYJE3U4Q36AA2E6HFTGKCUXIBUB2NMIGAFDA
```

https://docs.symbolplatform.com/guides/network/creating-a-private-test-net.html#retrieving-the-test-accounts

3) `light` preset has been transformed into a bootstrap assembly

`symbol-bootstrap -p bootstrap -a light` 

Note that -p bootstrap is optional, it can actually be `symbol-bootstrap -a light` 

https://docs.symbolplatform.com/guides/network/using-symbol-bootstrap.html#configuration
